import "../sass/styles.sass";
import "../scripts/fadeOutOnTransition.js";
import "../scripts/formSubmit.js";
import "../scripts/navScroll.js";
import "../scripts/openCloseMenu.js";
import "../scripts/smoothScroll.js";
import "../scripts/startLazyLoad.js";
import "../scripts/swRegister.js";
import "../scripts/webShare.js";