# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.15

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo
    
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: 
          name: Install Build Dependencies
          command: npm install
      - run: 
          name: Build
          command: npm run build
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      
      # Persist the specified paths (workspace/echo-output) into the workspace for use in downstream job. 
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is 
          # taken to be the root directory of the workspace.
          root: ~/repo
          # Must be relative path from root
          paths:
            - .

  deploy:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.15

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4
    working_directory: ~/repo
    
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Install AWS dependencies
          command: |
            sudo apt update
            sudo apt install -y python-pip python-dev
            sudo pip install awscli
      - run:
          name: Deploy to S3
          command: |
            aws s3 sync dist s3://www.aranbc.com/ --delete
            aws s3 cp s3://www.aranbc.com/dynamo s3://www.aranbc.com/dynamo --content-type "text/html" --metadata-directive REPLACE
            aws s3 cp s3://www.aranbc.com/koodoo s3://www.aranbc.com/koodoo --content-type "text/html" --metadata-directive REPLACE
            aws s3 cp s3://www.aranbc.com/thankyou s3://www.aranbc.com/thankyou --content-type "text/html" --metadata-directive REPLACE
            aws s3 cp s3://www.aranbc.com/404 s3://www.aranbc.com/404 --content-type "text/html" --metadata-directive REPLACE
      - run: echo "WE'RE ONLINE"
      - save_cache:
          paths:
            - Pipfile
          key: v1-dependencies-{{ checksum "requirements.txt" }}

workflows:
  version: 2
  build and deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master